version: '3'

services: 
  app:
      build: .
      volumes: 
        - .:/onshop
      working_dir: /onshop
      container_name: onshop_shopping
      command: python main.py -m screen:droid2,portrait
